### ISSUE TITLE
Building instruction for Android

### ISSUE THREAD

**Issue by fntheirs** [manisandro/shapelib#1]
Hi! I know that this project had no commits for years but I was wondering if is it possible to compile shapelib for Android. I started to working with Android and I'm a newbie in the makefiles and compile things area.

Any hints, i.e. a replacement or something would be really appreciated.

Thanks!
Fernando

**Comment by manisandro** [comment]
Hi,
First off, I'm not actually upstream for shapelib, this repo is just a fork with an autotools based build system (instead of the hand-written Makefiles of the upstream project, which is pretty much dead though). Also, nowadays shapelib is developed and released as part of gdal, so if you're ok with using the full gdal your best shot is https://trac.osgeo.org/gdal/wiki/BuildingForAndroid .

**Comment by fntheirs** [comment]
Wow! That was fast! Thanks manisandro! I'll give it a look.
